version: '3.3'
volumes:
  db_data:
services:
  database:
    image: mysql:8.0.29
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cineDB
      MYSQL_USER: spq
      MYSQL_PASSWORD: spq
    ports:
      - "3307:3306"
  server:
    depends_on:
      - database
    build: .
    ports:
      - "8080:8080"
    restart: always